module.exports = {
    crowbar: {
        id: 'crowbar',
        name: 'Pied-de-biche',
        price: 300,
        description: '+10 % de réussite à l\'Épicerie si activé. Se brise en cas d\'échec.',
    },
    bolt_cutter: {
        id: 'bolt_cutter',
        name: 'Coupe-boulon',
        price: 600,
        description: '+10 % de réussite à la Bijouterie de quartier si activé. Se brise en cas d\'échec.',
    },
    jammer: {
        id: 'jammer',
        name: 'Brouilleur radio',
        price: 1000,
        description: 'Obligatoire pour braquer la Banque de quartier. Détruit en cas d\'échec.',
    },
    lockpick_kit: {
        id: 'lockpick_kit',
        name: 'Kit de crochetage pro',
        price: 1800,
        description: 'Obligatoire pour braquer le Magasin de luxe. Confisqué en cas d\'échec.',
    },
    drill: {
        id: 'drill',
        name: 'Perceuse thermique',
        price: 3500,
        description: 'Obligatoire pour braquer la Banque centrale. Détruite en cas d\'échec.',
    },
    police_badge: {
        id: 'police_badge',
        name: 'Badge d\'accès corrompu',
        price: 5000,
        description: 'Obligatoire pour infiltrer le Coffre des forces de l\'ordre. Confisqué en cas d\'échec.',
    },
    vest: {
        id: 'vest',
        name: 'Gilet pare-balles',
        price: 800,
        description: 'Consommable : évite la prison une fois en cas d\'échec.',
    },
    lawyer: {
        id: 'lawyer',
        name: 'Avocat véreux',
        price: 1200,
        description: 'Valable 1 heure : divise par deux la durée de tes peines de prison.',
    },
    key_bronze: {
        id: 'key_bronze',
        name: 'Clé en bronze',
        price: 1500,
        description: 'Multiplie par x2 les gains du casse. Consommée à la fin (succès ou échec).',
    },
    key_silver: {
        id: 'key_silver',
        name: 'Clé en argent',
        price: 3500,
        description: 'Multiplie par x3 les gains du casse. Consommée à la fin (succès ou échec).',
    },
    key_gold: {
        id: 'key_gold',
        name: 'Clé en or',
        price: 8000,
        description: 'Multiplie par x5 les gains du casse. Consommée à la fin (succès ou échec).',
    },
    key_diamond: {
        id: 'key_diamond',
        name: 'Clé en diamant',
        price: 20000,
        description: 'Multiplie par x10 les gains du casse. Consommée à la fin (succès ou échec).',
    },
    key_special: {
        id: 'key_special',
        name: 'Clé spéciale',
        price: 12000,
        description: 'Multiplie aléatoirement les gains (x2, x3, x5, x10 ou x20). Consommée à la fin (succès ou échec).',
    },
};